name: ASDF Cache plugin
description: Step level customizable Slack notifications
author: https://github.com/sourcegraph
requirements:
  - asdf
configuration:
  properties:
    bucket_name:
      type: string
    region:
      type: string
    disable:
      type: boolean
  additionalProperties: false
